// qwik/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";

export const useServerTime = routeLoader$(() => new Date().toISOString());

export default component$(() => {
  const renderedAt = useServerTime();
  return (
    <main>
      <h1>Qwik on Nitroship</h1>
      <p>This page is rendered on the server for each request.</p>
      <p>Server render time: <time>{renderedAt.value}</time></p>
      <p><a href="/api/info">JSON server route</a> · <a href="/marker.txt">Public asset</a></p>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Qwik on Nitroship",
  meta: [{ name: "description", content: "Request-time Qwik City SSR on Nitroship." }],
};

// tanstack-start/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/react-start'

const getServerInfo = createServerFn({ method: 'GET' }).handler(() => ({
  framework: 'tanstack-start',
  serverTime: new Date().toISOString(),
}))

export const Route = createFileRoute('/')({
  loader: () => getServerInfo(),
  component: Home,
})

function Home() {
  const info = Route.useLoaderData()
  return (
    <main>
      <h1>TanStack Start on Nitroship</h1>
      <p>This page is rendered with a server function for each request.</p>
      <p>Server time: <time>{info.serverTime}</time></p>
      <p><a href="/api/info">JSON server route</a></p>
      <p><a href="/example.svg">Public asset served by the CDN</a></p>
      <img src="/example.svg" alt="Nitroship example" width="160" height="80" />
    </main>
  )
}
