// qwik/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";

export const useServerTime = routeLoader$(() => new Date().toISOString());

export default component$(() => {
  const renderedAt = useServerTime();
  return (
    <main>
      <h1>Qwik on Nitroship</h1>
      <p>This page is rendered on the server for each request.</p>
      <p>Server render time: <time>{renderedAt.value}</time></p>
      <p><a href="/api/info">JSON server route</a> · <a href="/marker.txt">Public asset</a></p>
    </main>
  );
});

export const head: DocumentHead = {
  title: "Qwik on Nitroship",
  meta: [{ name: "description", content: "Request-time Qwik City SSR on Nitroship." }],
};

// solidstart/src/routes/index.tsx
import { createAsync, query } from "@solidjs/router";

const getServerTime = query(async () => {
  "use server";
  return new Date().toISOString();
}, "server-time");

export const route = { preload: () => getServerTime() };

export default function Home() {
  const serverTime = createAsync(() => getServerTime());
  return (
    <main>
      <h1>SolidStart on Nitroship</h1>
      <p>Server-rendered at <time>{serverTime()}</time></p>
      <p>The timestamp comes from a server-only query, not the browser.</p>
      <p><a href="/api/hello">Server JSON</a> · <a href="/marker.txt">CDN asset</a></p>
    </main>
  );
}
